# Generated by Django 6.1.1 on 2026-09-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidence_approval_notes_evidence_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodytransfer',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custodytransfer',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custodytransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Acceptance'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
