# Generated by Django 6.1.1 on 2026-09-10 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('role_in_case', models.CharField(choices=[('SUSPECT', 'Suspect'), ('WITNESS', 'Witness'), ('VICTIM', 'Victim'), ('PERSON_OF_INTEREST', 'Person of Interest')], default='SUSPECT', max_length=50)),
                ('identification_number', models.CharField(blank=True, help_text='Aadhaar, Passport, or Govt ID ref', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons_of_interest', to='cases.case')),
            ],
        ),
    ]
