# Generated by Django 6.1.1 on 2026-09-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='classification',
            field=models.CharField(choices=[('INTERNAL', 'Internal / Restricted'), ('CONFIDENTIAL', 'Confidential'), ('HIGHLY_CONFIDENTIAL', 'Highly Confidential / Secret'), ('EVIDENCE', 'Evidentiary Record')], default='INTERNAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('FIR', 'First Information Report (FIR)'), ('FORENSIC_REPORT', 'Forensic Analysis Report'), ('WITNESS_STATEMENT', 'Witness Statement'), ('CHARGE_SHEET', 'Charge Sheet'), ('COURT_FILING', 'Court Filing'), ('LEGAL_NOTICE', 'Legal Notice'), ('JUDGMENT', 'Judgment / Court Order'), ('OTHER', 'Other Supporting Document')], default='OTHER', max_length=100),
        ),
    ]
