# Generated by Django 6.1.1 on 2026-09-10 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_classification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=64, unique=True)),
                ('signature_hex', models.TextField()),
                ('public_key_pem', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.CharField(default='RSA-PSS-SHA256', max_length=32)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures_rendered', to=settings.AUTH_USER_MODEL)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='documents.documentversion')),
            ],
        ),
    ]
