server {
    listen 80;
    server_name _;

    client_max_body_size 50M;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /home/ubuntu/sih-2026/staticfiles/;
    }

    location /media/ {
        alias /home/ubuntu/sih-2026/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/sih-2026/gunicorn.sock;
    }
}
