# Generated by Django 6.1.1 on 2026-09-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transactions', models.JSONField(default=list)),
                ('previous_hash', models.CharField(max_length=64)),
                ('block_hash', models.CharField(max_length=64, unique=True)),
                ('nonce', models.PositiveIntegerField(default=0)),
                ('merkle_root', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
