# Generated by Django 6.1.1 on 2026-09-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_details_auditlog_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveIntegerField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('merkle_root', models.CharField(max_length=64)),
                ('previous_block_hash', models.CharField(max_length=64)),
                ('nonce', models.IntegerField(default=0)),
                ('block_hash', models.CharField(max_length=64, unique=True)),
                ('event_count', models.IntegerField(default=0)),
                ('is_anchored', models.BooleanField(default=True)),
                ('tx_receipt', models.CharField(blank=True, help_text='Consortium simulated transaction hash', max_length=66)),
            ],
        ),
        migrations.AddField(
            model_name='auditlog',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='audit.block'),
        ),
    ]
