# Generated by Django 6.1.1 on 2026-09-10 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_block_auditlog_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='audit.block'),
        ),
    ]
