# Generated by Django 6.1.1 on 2026-09-10 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_alter_document_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('key_findings', models.JSONField(default=list)),
                ('entities', models.JSONField(default=dict)),
                ('suggested_type', models.CharField(blank=True, max_length=50)),
                ('suggested_classification', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('extraction_method', models.CharField(default='PYPDF_TEXT', max_length=50)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_text', to='documents.document')),
            ],
        ),
    ]
